---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - debug: msg="it works!"

  - name: Create a JIRA issue
    uri:
        url: http://api.open-notify.org/astros.json
        user: your_username
        password: your_pass
        method: GET
        body: "{{ lookup('file','issue.json') }}"
        
        body_format: json
